// Stripe product & price mapping
export const PRODUCTS = {
  abo2ans: {
    id: "abo-2-ans",
    name: "Abonnement 2 ans — 12 numéros",
    price: 48,
    price_id: "price_1T11hVKbRd4yKDMHHCpMLRc3",
    product_id: "prod_Tyzgq3QeYl52IS",
    mode: "subscription" as const,
    interval: "2 ans",
    description: "Le choix malin : 4€ le numéro au lieu de 6,50€",
    features: [
      "12 numéros livrés chez vous",
      "Cadeau de bienvenue exclusif",
      "Accès illimité aux archives numériques",
      "Invitations événements VIP",
      "—25% vs. achat au numéro",
    ],
  },
  abo1an: {
    id: "abo-1-an",
    name: "Abonnement 1 an — 6 numéros",
    price: 26.5,
    price_id: "price_1T11hkKbRd4yKDMH6WlS54AH",
    product_id: "prod_Tyzho0muIqVKsX",
    mode: "subscription" as const,
    interval: "1 an",
    description: "6 numéros livrés + version numérique offerte",
    features: [
      "6 numéros livrés chez vous",
      "Version numérique incluse",
      "Accès archives (1 an)",
      "Newsletter conseils exclusifs",
    ],
  },
  abo6mois: {
    id: "abo-6-mois",
    name: "Abonnement 6 mois — 3 numéros",
    price: 14.5,
    price_id: "price_1T11i1KbRd4yKDMHppfC8rE9",
    product_id: "prod_Tyzh45p7SqdgGh",
    mode: "subscription" as const,
    interval: "6 mois",
    description: "L'idéal pour découvrir, livraison offerte",
    features: [
      "3 numéros livrés chez vous",
      "Livraison offerte en France",
      "Accès articles en ligne",
    ],
  },
  numeroCourant: {
    id: "numero-courant",
    name: "Le numéro en cours",
    price: 6.5,
    price_id: "price_1T11jSKbRd4yKDMHeJwcET6L",
    product_id: "prod_TyziMCpsgR7ham",
    mode: "payment" as const,
    description: "L'édition actuelle livrée chez vous",
    features: [
      "Magazine papier haute qualité",
      "Livraison incluse",
      "Accès aux articles en ligne",
    ],
  },
  ancienNumero: {
    id: "ancien-numero",
    name: "Ancien numéro",
    price: 5,
    price_id: "price_1T11jkKbRd4yKDMHX2rIHogS",
    product_id: "prod_TyzjBfXTeN7CJT",
    mode: "payment" as const,
    description: "Ancien numéro d'Info Pêche",
    features: [
      "Magazine papier",
      "Livraison incluse",
    ],
  },
  lectureNumero: {
    id: "lecture-numero",
    name: "Lecture en ligne — 1 numéro",
    price: 3,
    price_id: "price_1T123wKbRd4yKDMH1bI9GQqh",
    product_id: "prod_Tz04LUvBZepwQ8",
    mode: "payment" as const,
    description: "Accès en ligne à un numéro d'Info Pêche",
    features: [
      "Consultation en ligne immédiate",
      "Accès permanent au numéro",
    ],
  },
  pass15jours: {
    id: "pass-15-jours",
    name: "Pass lecture 15 jours",
    price: 30,
    price_id: "price_1T124FKbRd4yKDMHYO6acPe1",
    product_id: "prod_Tz04Q4hOdHdp0D",
    mode: "payment" as const,
    description: "Accès illimité pendant 15 jours à tous les anciens numéros en ligne",
    features: [
      "Tous les anciens numéros",
      "15 jours d'accès illimité",
      "Consultation en ligne",
    ],
  },
} as const;

export type ProductKey = keyof typeof PRODUCTS;
